# Generated by Django 5.2.7 on 2025-11-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiques', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='morceau',
            name='date_sortie',
            field=models.DateField(null=True),
        ),
    ]
