# Generated by Django 5.2.7 on 2025-11-26 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiques', '0002_morceau_date_sortie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artiste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='morceau',
            name='artistetemp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musiques.artiste'),
        ),
    ]
