# Generated by Django 5.2.7 on 2025-11-26 14:51

from django.db import migrations


def migrer_artiste(apps, schema):
    Morceau = apps.get_model('musiques', 'Morceau')
    Artiste = apps.get_model('musiques', 'Artiste')
    artistes_connus = [f['artiste'] for f in Morceau.objects.all().values('artiste').distinct()]
    for artiste in artistes_connus:
        Artiste.objects.create(nom=artiste)

def annuler_migrer_artiste(apps, schema):
    Artiste = apps.get_model('musiques', 'Artiste')
    Artiste.objects.all().delete()

class Migration(migrations.Migration):
    dependencies = [('musiques', '0003_artiste_morceau_artistetemp'),]
    operations = [migrations.RunPython(migrer_artiste, reverse_code=annuler_migrer_artiste)]