# Generated by Django 5.2.7 on 2025-11-26 15:14

from django.db import migrations

def migrer_artiste(apps, schema_editor):
    Morceau = apps.get_model('musiques', 'Morceau')
    Artiste = apps.get_model('musiques', 'Artiste')
    artiste_connus = Artiste.objects.all()
    for artiste in artiste_connus:
        Artiste.objects.filter(nom=artiste.nom).update(nom=artiste.nom)

def annuler_migrer_artiste(apps, schema_editor):
    Artiste = apps.get_model('musiques', 'Artiste')
    Artiste.objects.all().delete()

class Migration(migrations.Migration):
    dependencies = [('musiques', '0004_auto_20251126_1551'),]

    operations = [
        migrations.RunPython(migrer_artiste, reverse_code=annuler_migrer_artiste),
    ]

