# Generated by Django 5.2.7 on 2025-11-26 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiques', '0005_auto_20251126_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morceau',
            name='artistetemp',
        ),
        migrations.AlterField(
            model_name='morceau',
            name='artiste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musiques.artiste'),
        ),
    ]
